@auth_token = auth_token

### GET all lunch orders
GET http://localhost:3000/lunch-orders
Authorization: Bearer {{auth_token}}
Accept: application/json

### ADD lunch orders for Jenny Green
POST http://localhost:3000/lunch-orders
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "weekdays": ["MONDAY", "WEDNESDAY", "FRIDAY"]
}

### ADD items to Monday's lunch
POST http://localhost:3000/lunch-orders/items
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "weekday": "MONDAY",
  "lunchItems" : ["strawberries", "potato chips", "veggie wrap", "chocolate chip cookies"]
}